/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface BikeLibInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "BikeValidated"
      | "InsuranceCalculated"
      | "LocationUpdated"
      | "ValidationError"
  ): EventFragment;
}

export namespace BikeValidatedEvent {
  export type InputTuple = [bikeId: BigNumberish, isValid: boolean];
  export type OutputTuple = [bikeId: bigint, isValid: boolean];
  export interface OutputObject {
    bikeId: bigint;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InsuranceCalculatedEvent {
  export type InputTuple = [bikeId: BigNumberish, rate: BigNumberish];
  export type OutputTuple = [bikeId: bigint, rate: bigint];
  export interface OutputObject {
    bikeId: bigint;
    rate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LocationUpdatedEvent {
  export type InputTuple = [bikeId: BigNumberish, locationHash: BytesLike];
  export type OutputTuple = [bikeId: bigint, locationHash: string];
  export interface OutputObject {
    bikeId: bigint;
    locationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationErrorEvent {
  export type InputTuple = [bikeId: BigNumberish, message: string];
  export type OutputTuple = [bikeId: bigint, message: string];
  export interface OutputObject {
    bikeId: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BikeLib extends BaseContract {
  connect(runner?: ContractRunner | null): BikeLib;
  waitForDeployment(): Promise<this>;

  interface: BikeLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BikeValidated"
  ): TypedContractEvent<
    BikeValidatedEvent.InputTuple,
    BikeValidatedEvent.OutputTuple,
    BikeValidatedEvent.OutputObject
  >;
  getEvent(
    key: "InsuranceCalculated"
  ): TypedContractEvent<
    InsuranceCalculatedEvent.InputTuple,
    InsuranceCalculatedEvent.OutputTuple,
    InsuranceCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "LocationUpdated"
  ): TypedContractEvent<
    LocationUpdatedEvent.InputTuple,
    LocationUpdatedEvent.OutputTuple,
    LocationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationError"
  ): TypedContractEvent<
    ValidationErrorEvent.InputTuple,
    ValidationErrorEvent.OutputTuple,
    ValidationErrorEvent.OutputObject
  >;

  filters: {
    "BikeValidated(uint256,bool)": TypedContractEvent<
      BikeValidatedEvent.InputTuple,
      BikeValidatedEvent.OutputTuple,
      BikeValidatedEvent.OutputObject
    >;
    BikeValidated: TypedContractEvent<
      BikeValidatedEvent.InputTuple,
      BikeValidatedEvent.OutputTuple,
      BikeValidatedEvent.OutputObject
    >;

    "InsuranceCalculated(uint256,uint256)": TypedContractEvent<
      InsuranceCalculatedEvent.InputTuple,
      InsuranceCalculatedEvent.OutputTuple,
      InsuranceCalculatedEvent.OutputObject
    >;
    InsuranceCalculated: TypedContractEvent<
      InsuranceCalculatedEvent.InputTuple,
      InsuranceCalculatedEvent.OutputTuple,
      InsuranceCalculatedEvent.OutputObject
    >;

    "LocationUpdated(uint256,bytes32)": TypedContractEvent<
      LocationUpdatedEvent.InputTuple,
      LocationUpdatedEvent.OutputTuple,
      LocationUpdatedEvent.OutputObject
    >;
    LocationUpdated: TypedContractEvent<
      LocationUpdatedEvent.InputTuple,
      LocationUpdatedEvent.OutputTuple,
      LocationUpdatedEvent.OutputObject
    >;

    "ValidationError(uint256,string)": TypedContractEvent<
      ValidationErrorEvent.InputTuple,
      ValidationErrorEvent.OutputTuple,
      ValidationErrorEvent.OutputObject
    >;
    ValidationError: TypedContractEvent<
      ValidationErrorEvent.InputTuple,
      ValidationErrorEvent.OutputTuple,
      ValidationErrorEvent.OutputObject
    >;
  };
}
