/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Klunkaz {
  export type BikeDetailsStruct = {
    bikeBrand: string;
    bikeTitle: string;
    bikeSize: string;
    bikeColor: string;
    bikeFrame: string;
    bikeFork: string;
    bikeShock: string;
  };

  export type BikeDetailsStructOutput = [
    bikeBrand: string,
    bikeTitle: string,
    bikeSize: string,
    bikeColor: string,
    bikeFrame: string,
    bikeFork: string,
    bikeShock: string
  ] & {
    bikeBrand: string;
    bikeTitle: string;
    bikeSize: string;
    bikeColor: string;
    bikeFrame: string;
    bikeFork: string;
    bikeShock: string;
  };

  export type BikeMetadataStruct = {
    category: string;
    images: string;
    bikeFeatures: string;
    isStolen: boolean;
    isInsured: boolean;
    listingType: BigNumberish;
    rentalPrice: BigNumberish;
    isRented: boolean;
    currentRenter: AddressLike;
    rentalEndTime: BigNumberish;
    securityDeposit: BigNumberish;
  };

  export type BikeMetadataStructOutput = [
    category: string,
    images: string,
    bikeFeatures: string,
    isStolen: boolean,
    isInsured: boolean,
    listingType: bigint,
    rentalPrice: bigint,
    isRented: boolean,
    currentRenter: string,
    rentalEndTime: bigint,
    securityDeposit: bigint
  ] & {
    category: string;
    images: string;
    bikeFeatures: string;
    isStolen: boolean;
    isInsured: boolean;
    listingType: bigint;
    rentalPrice: bigint;
    isRented: boolean;
    currentRenter: string;
    rentalEndTime: bigint;
    securityDeposit: bigint;
  };

  export type BikeStruct = {
    productID: BigNumberish;
    owner: AddressLike;
    price: BigNumberish;
    details: Klunkaz.BikeDetailsStruct;
    metadata: Klunkaz.BikeMetadataStruct;
  };

  export type BikeStructOutput = [
    productID: bigint,
    owner: string,
    price: bigint,
    details: Klunkaz.BikeDetailsStructOutput,
    metadata: Klunkaz.BikeMetadataStructOutput
  ] & {
    productID: bigint;
    owner: string;
    price: bigint;
    details: Klunkaz.BikeDetailsStructOutput;
    metadata: Klunkaz.BikeMetadataStructOutput;
  };

  export type ReviewStruct = {
    reviewer: AddressLike;
    rating: BigNumberish;
    comment: string;
    timestamp: BigNumberish;
  };

  export type ReviewStructOutput = [
    reviewer: string,
    rating: bigint,
    comment: string,
    timestamp: bigint
  ] & { reviewer: string; rating: bigint; comment: string; timestamp: bigint };
}

export interface KlunkazInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReview"
      | "approve"
      | "balanceOf"
      | "bikeIndex"
      | "endRental"
      | "getApproved"
      | "getBike"
      | "getProductReviews"
      | "getRentalHistory"
      | "isApprovedForAll"
      | "listBike"
      | "markAsStolen"
      | "name"
      | "owner"
      | "ownerOf"
      | "renounceOwnership"
      | "rentBike"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "updatePrice"
      | "verifyUser"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BikeListed"
      | "BikeRented"
      | "OwnershipTransferred"
      | "RentalEnded"
      | "ReviewAdded"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReview",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "bikeIndex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "endRental",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBike",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductReviews",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRentalHistory",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listBike",
    values: [
      BigNumberish,
      Klunkaz.BikeDetailsStruct,
      Klunkaz.BikeMetadataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsStolen",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rentBike",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyUser",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addReview", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bikeIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endRental", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBike", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProductReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRentalHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listBike", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markAsStolen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rentBike", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyUser", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BikeListedEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [id: bigint, owner: string, price: bigint];
  export interface OutputObject {
    id: bigint;
    owner: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BikeRentedEvent {
  export type InputTuple = [
    bikeId: BigNumberish,
    renter: AddressLike,
    duration: BigNumberish
  ];
  export type OutputTuple = [bikeId: bigint, renter: string, duration: bigint];
  export interface OutputObject {
    bikeId: bigint;
    renter: string;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RentalEndedEvent {
  export type InputTuple = [bikeId: BigNumberish, renter: AddressLike];
  export type OutputTuple = [bikeId: bigint, renter: string];
  export interface OutputObject {
    bikeId: bigint;
    renter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewAddedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    reviewer: AddressLike,
    rating: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    reviewer: string,
    rating: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    reviewer: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Klunkaz extends BaseContract {
  connect(runner?: ContractRunner | null): Klunkaz;
  waitForDeployment(): Promise<this>;

  interface: KlunkazInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReview: TypedContractMethod<
    [productId: BigNumberish, rating: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  bikeIndex: TypedContractMethod<[], [bigint], "view">;

  endRental: TypedContractMethod<[bikeId: BigNumberish], [void], "nonpayable">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getBike: TypedContractMethod<
    [id: BigNumberish],
    [Klunkaz.BikeStructOutput],
    "view"
  >;

  getProductReviews: TypedContractMethod<
    [productId: BigNumberish],
    [Klunkaz.ReviewStructOutput[]],
    "view"
  >;

  getRentalHistory: TypedContractMethod<
    [bikeId: BigNumberish, renter: AddressLike],
    [bigint[]],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  listBike: TypedContractMethod<
    [
      price: BigNumberish,
      details: Klunkaz.BikeDetailsStruct,
      metadata: Klunkaz.BikeMetadataStruct
    ],
    [bigint],
    "nonpayable"
  >;

  markAsStolen: TypedContractMethod<
    [bikeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rentBike: TypedContractMethod<
    [bikeId: BigNumberish, durationInDays: BigNumberish],
    [void],
    "payable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [bikeId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyUser: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReview"
  ): TypedContractMethod<
    [productId: BigNumberish, rating: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "bikeIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "endRental"
  ): TypedContractMethod<[bikeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getBike"
  ): TypedContractMethod<
    [id: BigNumberish],
    [Klunkaz.BikeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductReviews"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [Klunkaz.ReviewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRentalHistory"
  ): TypedContractMethod<
    [bikeId: BigNumberish, renter: AddressLike],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listBike"
  ): TypedContractMethod<
    [
      price: BigNumberish,
      details: Klunkaz.BikeDetailsStruct,
      metadata: Klunkaz.BikeMetadataStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markAsStolen"
  ): TypedContractMethod<[bikeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rentBike"
  ): TypedContractMethod<
    [bikeId: BigNumberish, durationInDays: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [bikeId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyUser"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BikeListed"
  ): TypedContractEvent<
    BikeListedEvent.InputTuple,
    BikeListedEvent.OutputTuple,
    BikeListedEvent.OutputObject
  >;
  getEvent(
    key: "BikeRented"
  ): TypedContractEvent<
    BikeRentedEvent.InputTuple,
    BikeRentedEvent.OutputTuple,
    BikeRentedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RentalEnded"
  ): TypedContractEvent<
    RentalEndedEvent.InputTuple,
    RentalEndedEvent.OutputTuple,
    RentalEndedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewAdded"
  ): TypedContractEvent<
    ReviewAddedEvent.InputTuple,
    ReviewAddedEvent.OutputTuple,
    ReviewAddedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BikeListed(uint256,address,uint256)": TypedContractEvent<
      BikeListedEvent.InputTuple,
      BikeListedEvent.OutputTuple,
      BikeListedEvent.OutputObject
    >;
    BikeListed: TypedContractEvent<
      BikeListedEvent.InputTuple,
      BikeListedEvent.OutputTuple,
      BikeListedEvent.OutputObject
    >;

    "BikeRented(uint256,address,uint256)": TypedContractEvent<
      BikeRentedEvent.InputTuple,
      BikeRentedEvent.OutputTuple,
      BikeRentedEvent.OutputObject
    >;
    BikeRented: TypedContractEvent<
      BikeRentedEvent.InputTuple,
      BikeRentedEvent.OutputTuple,
      BikeRentedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RentalEnded(uint256,address)": TypedContractEvent<
      RentalEndedEvent.InputTuple,
      RentalEndedEvent.OutputTuple,
      RentalEndedEvent.OutputObject
    >;
    RentalEnded: TypedContractEvent<
      RentalEndedEvent.InputTuple,
      RentalEndedEvent.OutputTuple,
      RentalEndedEvent.OutputObject
    >;

    "ReviewAdded(uint256,address,uint256)": TypedContractEvent<
      ReviewAddedEvent.InputTuple,
      ReviewAddedEvent.OutputTuple,
      ReviewAddedEvent.OutputObject
    >;
    ReviewAdded: TypedContractEvent<
      ReviewAddedEvent.InputTuple,
      ReviewAddedEvent.OutputTuple,
      ReviewAddedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
