/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface BikeLibInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "BikeValidated"): EventFragment;
}

export namespace BikeValidatedEvent {
  export type InputTuple = [bikeId: BigNumberish, isValid: boolean];
  export type OutputTuple = [bikeId: bigint, isValid: boolean];
  export interface OutputObject {
    bikeId: bigint;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BikeLib extends BaseContract {
  connect(runner?: ContractRunner | null): BikeLib;
  waitForDeployment(): Promise<this>;

  interface: BikeLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BikeValidated"
  ): TypedContractEvent<
    BikeValidatedEvent.InputTuple,
    BikeValidatedEvent.OutputTuple,
    BikeValidatedEvent.OutputObject
  >;

  filters: {
    "BikeValidated(uint256,bool)": TypedContractEvent<
      BikeValidatedEvent.InputTuple,
      BikeValidatedEvent.OutputTuple,
      BikeValidatedEvent.OutputObject
    >;
    BikeValidated: TypedContractEvent<
      BikeValidatedEvent.InputTuple,
      BikeValidatedEvent.OutputTuple,
      BikeValidatedEvent.OutputObject
    >;
  };
}
